# Generated by Django 3.2.8 on 2021-11-13 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, default='username')),
                ('artist', models.TextField(blank=True, default='artist')),
                ('song_title', models.TextField(default='song')),
                ('album', models.TextField(blank=True, default='album', null=True)),
                ('date', models.TextField(default='date')),
                ('date_utc', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LastFmProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('password', models.TextField()),
            ],
        ),
    ]
