# Generated by Django 3.2.8 on 2021-11-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastfmprofile',
            name='username',
            field=models.TextField(default='user'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.lastfmprofile'),
        ),
    ]
