# Generated by Django 3.2.8 on 2021-11-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20211115_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='charts.lastfmprofile'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='username',
            field=models.TextField(blank=True, default='username'),
        ),
    ]
