# Generated by Django 3.2.8 on 2021-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='count',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
