# Generated by Django 3.2.8 on 2021-10-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('charts', '0003_chart_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFmProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LastUser',
        ),
        migrations.AlterField(
            model_name='chart',
            name='count',
            field=models.TextField(default=0, unique=True),
        ),
    ]
