# Generated by Django 3.2.8 on 2021-11-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20211115_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='user',
        ),
    ]
