# Generated by Django 3.2.8 on 2021-11-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_remove_chart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastFmProfile',
        ),
    ]
