# Generated by Django 3.2.8 on 2021-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20211025_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='info',
        ),
        migrations.AddField(
            model_name='chart',
            name='artist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chart',
            name='username',
            field=models.TextField(default='username'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='count',
            field=models.IntegerField(),
        ),
    ]
