# Generated by Django 3.2.8 on 2021-10-26 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20211026_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='count',
        ),
        migrations.AddField(
            model_name='chart',
            name='album',
            field=models.TextField(default='album'),
        ),
        migrations.AddField(
            model_name='chart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 21, 33, 20, 852782)),
        ),
        migrations.AddField(
            model_name='chart',
            name='song_title',
            field=models.TextField(default='song'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='artist',
            field=models.TextField(blank=True, default='artist'),
        ),
    ]
