# Generated by Django 3.2.8 on 2021-10-26 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20211026_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 21, 34, 22, 160986)),
        ),
    ]
