# Generated by Django 3.2.8 on 2021-10-26 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_alter_chart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 21, 36, 57, 805572)),
        ),
    ]
