# Generated by Django 3.2.8 on 2021-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_alter_chart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date',
            field=models.TextField(default='date'),
        ),
    ]
