# Generated by Django 3.2.8 on 2021-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_auto_20211026_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='album',
            field=models.TextField(blank=True, default='album', null=True),
        ),
    ]
