# Generated by Django 3.2.8 on 2021-10-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_alter_chart_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='date_utc',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 9, 46, 9, 992585)),
        ),
    ]
