# Generated by Django 3.2.8 on 2021-10-30 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0012_chart_date_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date_utc',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 10, 46, 25, 581654, tzinfo=utc)),
        ),
    ]
