# Generated by Django 3.2.8 on 2021-10-30 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_alter_chart_date_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date_utc',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 13, 57, 55, 598893)),
        ),
    ]
