# Generated by Django 3.2.8 on 2021-10-31 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_alter_chart_date_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='date_utc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
